language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

    exclude:
        - php: hhvm
          env: PHP_BIN=php-cgi

        - php: hhvm-nightly
          env: PHP_BIN=php-cgi

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --dev --prefer-source
    - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source
