language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   name: Nette Code Checker
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3.0 --no-progress
            script:
                - php temp/code-checker/code-checker --strict-types -i tests/Tracy/fixtures -i examples/assets


        -   name: Nette Coding Standard
            install:
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
            script:
                - php temp/coding-standard/ecs check src tests examples tools --config tests/coding-standard.yml


        -   name: Code Standard Checker (JS)
            install:
                # Install new Node.js and Eslint
                - . $HOME/.nvm/nvm.sh
                - nvm install stable
                - nvm use stable
                - npm install eslint
            script:
                - ./node_modules/.bin/eslint "src/**/*.js"


        -   stage: Static Analysis (informative)
            install:
                # Install PHPStan
                - travis_retry composer create-project phpstan/phpstan-shim temp/phpstan --no-progress
                - travis_retry composer install --no-progress --prefer-dist
            script:
                - php temp/phpstan/phpstan.phar analyse --autoload-file vendor/autoload.php --level 5 src


        -   stage: Code Coverage
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Static Analysis (informative)
        -   stage: Code Coverage


os: linux

dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
