language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.1
            install:
                # Install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-progress
                # Install Nette Coding Standard
                - travis_retry composer create-project nette/coding-standard temp/coding-standard --no-progress
                # Install new Node.js and Eslint
                - . $HOME/.nvm/nvm.sh
                - nvm install stable
                - nvm use stable
                - npm install
                - npm install eslint
            script:
                - php temp/code-checker/src/code-checker.php --short-arrays -i tests/Tracy/fixtures -i examples/assets
                - php temp/coding-standard/ecs check src tests examples tools --config tests/coding-standard.neon
                - ./node_modules/.bin/eslint "src/**/*.js"


        -   stage: Code Coverage
            php: 7.1
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml

        -   stage: Static Analysis
            php: 7.1
            script:
                - vendor/bin/psalm --show-info=false

    allow_failures:
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
